"""empty message

Revision ID: 523d6818a5e3
Revises: 6e53ac959075
Create Date: 2025-08-31 15:18:21.356321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '523d6818a5e3'
down_revision = '6e53ac959075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False, comment='应用状态'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment='应用ID',
               existing_nullable=False)
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               comment='应用账户ID',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment='应用名称',
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               comment='应用图标',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment='应用描述',
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='应用描述',
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='应用图标',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='应用名称',
               existing_nullable=False)
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='应用账户ID',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='应用ID',
               existing_nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
